#!/bin/bash
# Write a script that runs a C file through the preprocessor and saves the result into another file.
# The C file name will be stored in the variable $CFILE
# The output should be saved in the file c
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -E $CFILE -o c
