#!/bin/bash
# Write a script that compiles a C file but does not link.
# The C file name will be stored in the variable $CFILE
# The output file should have the same name as the C file, but with the extension .o
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -c $CFILE
