#!/bin/bash
# Write a script that generates the assembly code of a C code and saves it in an output file.
# The C file name will be stored in the variable $CFILE
# The output file should have the same name but with the extension .s
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -S $CFILE
